# Generated by Django 2.2.5 on 2020-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200219_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='img/ahiface.png', upload_to='uploads/%YYYY/%MM/%DD'),
        ),
    ]
